# Generated by Django 5.0.4 on 2024-05-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_slug_alter_blogpost_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.PositiveIntegerField(
                editable=False, verbose_name="Количество просмотров"
            ),
        ),
    ]
